// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"jt_chat/internal/dao/internal"
)

// internalContactApplicationDao is internal type for wrapping internal DAO implements.
type internalContactApplicationDao = *internal.ContactApplicationDao

// contactApplicationDao is the data access object for table contact_application.
// You can define custom methods on it to extend its functionality as you wish.
type contactApplicationDao struct {
	internalContactApplicationDao
}

var (
	// ContactApplication is globally public accessible object for table contact_application operations.
	ContactApplication = contactApplicationDao{
		internal.NewContactApplicationDao(),
	}
)

// Fill with you ideas below.
