// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"jt_chat/internal/dao/internal"
)

// internalUserContactsDao is internal type for wrapping internal DAO implements.
type internalUserContactsDao = *internal.UserContactsDao

// userContactsDao is the data access object for table user_contacts.
// You can define custom methods on it to extend its functionality as you wish.
type userContactsDao struct {
	internalUserContactsDao
}

var (
	// UserContacts is globally public accessible object for table user_contacts operations.
	UserContacts = userContactsDao{
		internal.NewUserContactsDao(),
	}
)

// Fill with you ideas below.
