// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"jt_chat/internal/dao/internal"
)

// internalUserGroupMapDao is internal type for wrapping internal DAO implements.
type internalUserGroupMapDao = *internal.UserGroupMapDao

// userGroupMapDao is the data access object for table user_group_map.
// You can define custom methods on it to extend its functionality as you wish.
type userGroupMapDao struct {
	internalUserGroupMapDao
}

var (
	// UserGroupMap is globally public accessible object for table user_group_map operations.
	UserGroupMap = userGroupMapDao{
		internal.NewUserGroupMapDao(),
	}
)

// Fill with you ideas below.
